---
apiVersion: v1
kind: Namespace
metadata:
  name: innsecure
  labels:
    name: innsecure
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: innsecure
  labels:
    app: innsecure
data:
  01_init.sql: |
    CREATE TABLE "Bookings"
      (
      id UUID PRIMARY KEY NOT NULL,
      hotelid INTEGER NOT NULL,
      arrive TEXT NOT NULL,
      leave TEXT NOT NULL,
      name TEXT NOT NULL
    );
